addons: 
  apt: 
    packages: 
      - p7zip-full
    sources: ~
after_success: 
  - "ls -al artifacts/"
  - "cd artifacts/"
  - "wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh"
  - "chmod a+x upload.sh"
  - "bash upload.sh yuzu-x86_64.AppImage*"
branches: 
  except: 
    - "/^(?i:continuous.*)$/"
cache: ccache
compiler: 
  - gcc
deploy: 
  api_key: $GITHUB_TOKEN
  file: artifacts/*
  file_glob: true
  provider: releases
  skip_cleanup: true
  true: 
    tags: true
install: 
  - "mkdir -p \"$HOME/.ccache\""
  - "docker pull quriouspixel/yuzu:20.04"
language: cpp
script: 
  - "docker run -u root --env-file travis/common/travis-ci.env -v $(pwd):/dolphin -v \"$HOME/.ccache\":/root/.ccache quriouspixel/yuzu:20.04 /bin/bash /dolphin/travis/appimage/docker.sh"
services: docker
sudo: false
