name: Dolphin-AppImage

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  dolphin-appimage:
    # Name the Job
    name: dolphin bundled as appimage
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      # Runs the Dolphin action
      - name: cache
        uses: actions/cache@v2
      - name: install Dolphin
        run:  mkdir -p "$HOME/.ccache"
        run:  docker pull quriouspixel/dolphin:18.04
        run:  docker run -u root --env-file travis/common/travis-ci.env -v $(pwd):/dolphin -v "$HOME/.ccache":/root/.ccache quriouspixel/dolphin:18.04 /bin/bash /dolphin/travis/appimage/docker.sh
      - name: Run Dolphin-AppImage
        run:  ls -al
        env:
          DEFAULT_BRANCH: git-actions
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
